CREATE DATABASE pruebapatrones2;

USE pruebapatrones2;

CREATE TABLE Poblacion (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ANO INT,
    CODIGO_LOCALIDAD VARCHAR(255),
    NOMBRE_LOCALIDAD VARCHAR(255),
    SEXO VARCHAR(10),
    EDAD INT,
    CURSODEVIDA VARCHAR(255),
    GRUPOEDAD VARCHAR(255),
    POBLACION_7 INT
);

CREATE TABLE Programa1 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    REGIMEN_DE_AFILIACION VARCHAR(255),
    LOCALIDAD_CALCULADA VARCHAR(255),
    ASEGURADOR VARCHAR(255),
    FECHA_DE_NACIMIENTO_USUARIO DATE,
    SEXO CHAR(10),
    FECHA_DE_LA_CONSULTA DATE,
    NACIONALIDAD VARCHAR(255)
);

CREATE TABLE Programa2 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    SEXO_BIOLOGICO CHAR(1),
    LOCALIDAD VARCHAR(255),
    EAPB VARCHAR(255),
    FECHA_DE_NACIMIENTO DATE,
    PERTENENCIA_ETNICA VARCHAR(255),
    SEXO_BIOLOGICO_1 CHAR(40),
    RIESGO_PSICOSOCIAL VARCHAR(255),
    FECHA_DE_LA_CONSULTA DATE,
    TALLA INT
);

CREATE TABLE Programa3 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    LOCALIDADFIC_3 VARCHAR(255),
    NACIONALIDAD_10 VARCHAR(255),
    NOMBREEAPB_27 VARCHAR(255),
    FECHADENACIMIENTO_14 DATE,
    ETNIA_18 VARCHAR(255),
    SEXO_11 CHAR(40),
    GENERO_12 VARCHAR(255),
    FECHAINTERVENCION_2 DATE
);

CREATE TABLE Programa4 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    LOCALIDAD_FIC VARCHAR(255),
    ESTADO_CIVIL_ VARCHAR(255),
    NOMBRE_EAPB_ VARCHAR(255),
    FECHA_DE_NACIMIENTO_ DATE,
    ETNIA_ VARCHAR(255),
    SEXO_ CHAR(255),
    FECHA_INTERVENCION DATE
);

SHOW VARIABLES LIKE 'local_infile';
SET GLOBAL local_infile = 1;

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\POBLACION.txt'
INTO TABLE Poblacion
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(ANO, CODIGO_LOCALIDAD, NOMBRE_LOCALIDAD, SEXO, EDAD, CURSODEVIDA, GRUPOEDAD, POBLACION_7);

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\PROGRAMA_1_corrected.txt'
INTO TABLE Programa1
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(REGIMEN_DE_AFILIACION, LOCALIDAD_CALCULADA, ASEGURADOR, FECHA_DE_NACIMIENTO_USUARIO, SEXO, FECHA_DE_LA_CONSULTA, NACIONALIDAD);

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\PROGRAMA_2_corrected.txt'
INTO TABLE Programa2
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(SEXO_BIOLOGICO, LOCALIDAD, EAPB, FECHA_DE_NACIMIENTO, PERTENENCIA_ETNICA, SEXO_BIOLOGICO_1, RIESGO_PSICOSOCIAL, FECHA_DE_LA_CONSULTA, TALLA);

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\PROGRAMA_3_corrected.txt'
INTO TABLE Programa3
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(LOCALIDADFIC_3, NACIONALIDAD_10, NOMBREEAPB_27, FECHADENACIMIENTO_14, ETNIA_18, SEXO_11, GENERO_12, FECHAINTERVENCION_2);

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\PROGRAMA_4_corrected.txt'
INTO TABLE Programa4
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(LOCALIDAD_FIC, ESTADO_CIVIL_, NOMBRE_EAPB_, FECHA_DE_NACIMIENTO_, ETNIA_, SEXO_, FECHA_INTERVENCION);

CREATE VIEW VISTA_CONSOLIDADO AS
SELECT 
    COALESCE(Programa1.LOCALIDAD_CALCULADA, Programa2.LOCALIDAD, Programa3.LOCALIDADFIC_3) AS Localidad,
    COALESCE(Programa1.SEXO, Programa2.SEXO_BIOLOGICO, Programa3.SEXO_11) AS Sexo,
    COALESCE(Programa1.FECHA_DE_NACIMIENTO_USUARIO, Programa2.FECHA_DE_NACIMIENTO, Programa3.FECHADENACIMIENTO_14) AS FechaNacimiento,
    COALESCE(Programa1.ASEGURADOR, Programa2.EAPB, Programa3.NOMBREEAPB_27) AS Asegurador,
    COALESCE(Programa1.NACIONALIDAD, Programa3.NACIONALIDAD_10) AS Nacionalidad, -- Eliminada Programa2
    COALESCE(Programa1.FECHA_DE_LA_CONSULTA, Programa2.FECHA_DE_LA_CONSULTA, Programa3.FECHAINTERVENCION_2) AS FechaConsulta,
    COALESCE(Programa1.REGIMEN_DE_AFILIACION, Programa2.RIESGO_PSICOSOCIAL, Programa3.ETNIA_18) AS RegimenAfiliacion
FROM Programa1
LEFT JOIN Programa2 ON Programa1.id = Programa2.id
LEFT JOIN Programa3 ON Programa1.id = Programa3.id;

CREATE VIEW VISTA_INDICADORES AS
SELECT 
    COALESCE(Programa1.LOCALIDAD_CALCULADA, Programa2.LOCALIDAD, Programa3.LOCALIDADFIC_3) AS Localidad,
    COALESCE(Programa1.SEXO, Programa2.SEXO_BIOLOGICO, Programa3.SEXO_11) AS Sexo,
    COUNT(*) AS TotalRegistros,
    COUNT(DISTINCT COALESCE(Programa1.ASEGURADOR, Programa2.EAPB, Programa3.NOMBREEAPB_27)) AS TotalAseguradores,
    AVG(YEAR(CURDATE()) - YEAR(COALESCE(Programa1.FECHA_DE_NACIMIENTO_USUARIO, Programa2.FECHA_DE_NACIMIENTO, Programa3.FECHADENACIMIENTO_14))) AS EdadPromedio
FROM Programa1
LEFT JOIN Programa2 ON Programa1.id = Programa2.id
LEFT JOIN Programa3 ON Programa1.id = Programa3.id
GROUP BY 
    COALESCE(Programa1.LOCALIDAD_CALCULADA, Programa2.LOCALIDAD, Programa3.LOCALIDADFIC_3),
    COALESCE(Programa1.SEXO, Programa2.SEXO_BIOLOGICO, Programa3.SEXO_11);

SELECT * 
INTO OUTFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\VISTA_CONSOLIDADO.txt'
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
FROM VISTA_CONSOLIDADO;

SELECT * 
INTO OUTFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\VISTA_INDICADORES.txt'
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
FROM VISTA_INDICADORES;